name: 'R-actions'
description: 'Automatically build and test your R projects'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  action:  # id of input  
    description: 'What should be run? One of: ["all", "build"]'
    default: 'all'
  needsBioc: 
    description: 'Is Bioconductor package needed? One of [true, false]'
    default: false
  buildSubDirectory:
    description: 'The path saving source code of package in repository'
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.action}}
    - ${{inputs.needsBioc}}
    - ${{inputs.buildSubDirectory}}
